[start]
command:/usr/local/etc/rc.d/os-lightscope start
type:script
message:starting lightscope service

[stop]
command:/usr/local/etc/rc.d/os-lightscope stop
type:script
message:stopping lightscope service

[restart]
command:/usr/local/etc/rc.d/os-lightscope restart
type:script
message:restarting lightscope service

[status]
command:/usr/local/etc/rc.d/os-lightscope status; exit 0
type:script_output
message:requesting lightscope status

[reconfigure]
command:/usr/local/opnsense/scripts/lightscope/reconfigure.sh
type:script
message:reconfiguring lightscope
description:Regenerate lightscope configuration
