PLUGIN_NAME=		lightscope
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		LightScope network security monitoring
PLUGIN_MAINTAINER=	eric@thelightscope.com
PLUGIN_WWW=		https://thelightscope.com
PLUGIN_DEPENDS=		python311 py311-dpkt py311-requests py311-psutil

.include "../../Mk/plugins.mk"
